                                                                                      setTodos([...todos, newTodoItem]);
                                                                                          
                                                                                              // Clear the input field after adding
                                                                                                  setNewTodo('');
                                                                                                    };

                                                                                                      // Function to toggle the 'completed' status of a todo
                                                                                                        const toggleComplete = (id) => {
                                                                                                            setTodos(todos.map(todo => 
                                                                                                                  todo.id === id ? { ...todo, completed: !todo.completed } : todo
                                                                                                                      ));
                                                                                                                        };

                                                                                                                          return (
                                                                                                                              <div className="app">
                                                                                                                                    <h1>Todo List</h1>
                                                                                                                                          
                                                                                                                                                {/* Update the Form for adding new todos */}
                                                                                                                                                      <form onSubmit={handleSubmit} className="todo-form">
                                                                                                                                                              <input
                                                                                                                                                                        type="text"
                                                                                                                                                                                  value={newTodo} // set the value
                                                                                                                                                                                            onChange={(e) => setNewTodo(e.target.value)} // set on change behaviour
                                                                                                                                                                                                      placeholder="Add a new todo..." // set placeholder
                                                                                                                                                                                                              />
                                                                                                                                                                                                                      <button type="submit">Add</button>
                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                  {/* Display the list of todos */}
                                                                                                                                                                                                                                        <div className="todo-list">
                                                                                                                                                                                                                                                {todos.length === 0 ? (
                                                                                                                                                                                                                                                          // Message shown when there are no todos
                                                                                                                                                                                                                                                                    <p className="empty-message">No todos</p>
                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                      // Map over todos to render each item
                                                                                                                                                                                                                                                                                                todos.map(todo => (
                                                                                                                                                                                                                                                                                                            <div key={todo.id} className={`todo-item ${todo.completed ? 'completed' : ''}`}>
                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                          type="checkbox"
                                                                                                                                                                                                                                                                                                                                                          checked={todo.completed}
                                                                                                                                                                                                                                                                                                                                                                          onChange={() => toggleComplete(todo.id)}
                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                      <span>{todo.text}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;